services:
  - type: web
    name: foodmood-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "src.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false 